In [2]:
# COMPUTACIÓN BLANDA - Sistemas y Computación
# -------------------------------------------
# Introducción a numpy
# Luis Anibal Loaiza C.
# -------------------------------------------
# Lección 01
#
# ** Creación de arrays
# ** Acceso a los arrays
# ** Manejo de rangos
# ** Modificación de arrays
#
# -------------------------------------------

In [10]:
# Se importa la librería numpy
import numpy as np
# Se crea una array con 6 elementos
a = np.arange(7)
# Se imprime en pantalla el contenido del array a
print('Arreglo a =', a, '\n')
# Se muestra el tipo de los elementos del array
print('Tipo de a =', a.dtype, '\n')
# Se calcula la dimensión del array a, en este caso dimensión = 1 (vector)
print('Dimensión de a =', a.ndim, '\n')
# Se calcula el número de elementos del array a
# No olvidar que existe un elemento con índice 0
print('Número de elementos de a =', a.shape,'\n')

print("Convertir arreglo de enteros a float:",'\n')

a=a.astype(float)

print(a,'\n')

print('Tipo de a =', a.dtype, '\n')

Arreglo a = [0 1 2 3 4 5 6] 

Tipo de a = int32 

Dimensión de a = 1 

Número de elementos de a = (7,) 

Convertir arreglo de enteros a float: 

[0. 1. 2. 3. 4. 5. 6.] 

Tipo de a = float64 



In [25]:
# Seleccionando elementos de un array
# De forma automatica

a = np.array([[1,2], [3,4], [5,6]])
print('a =\n', a, '\n')
for i in range(len(a)):
    for j in range(len(a[i])):
        print('a[{},{}] ='.format(i,j) , a[i][j],'\n')
            
# Elementos individuales
#print('a[0,0] =', a[0,0], '\n')
#print('a[0,1] =', a[0,1], '\n')
#print('a[1,0] =', a[1,0], '\n')
#print('a[1,1] =', a[1,1])

a =
 [[1 2]
 [3 4]
 [5 6]] 

a[0,0] = 1 

a[0,1] = 2 

a[1,0] = 3 

a[1,1] = 4 

a[2,0] = 5 

a[2,1] = 6 



In [40]:
# Crea un array con 9 elementos, desde 0 hasta 8

a = np.arange(12)
print('a =', a, '\n')
# Muestra los elementos desde 0 hasta 9. Imprime desde 0 hasta 8
print('a[0:9] = ', a[0:9], '\n')
# Muestra desde 3 hasta 7. Imprime desde 3 hasta 6
print('a[3,7] =', a[3:7], '\n')
#Lista en orden inverso
print('a[::-1] =',a[::-1])

a = [ 0  1  2  3  4  5  6  7  8  9 10 11] 

a[0:9] =  [0 1 2 3 4 5 6 7 8] 

a[3,7] = [3 4 5 6] 

a[::-1] = [11 10  9  8  7  6  5  4  3  2  1  0]


In [66]:
# Mostrando todos los elementos, desde el 0 hasta el 8, de uno en uno

a = np.arange(12)
#Se reemplaza el tamaño por len(a),para reducir la necesidad de saber por defecto el tamaño

print('a[0:{}:1] ='.format(len(a)), a[0:len(a):1], '\n')
# El mismo ejemplo, pero omitiendo el número 0 al principio, el cual no es necesario aquí
print('a[:{}:1] ='.format(len(a)), a[:len(a):1], '\n')
# Mostrando los números, de dos en dos
print('a[0:{}:2] ='.format(len(a)), a[0:len(a):2], '\n')
# Mostrando los números, de tres en tres
print('a[0:{}:3] ='.format(len(a)), a[0:len(a):3], '\n')
# Mostrando los números, de cuatro en cuatro
print('a[0:{}:4] ='.format(len(a)), a[0:len(a):4], '\n')

print('Ahora con el for', '\n')

#Realizado con for

for i in range(1,5):
    print('a[:{}:{}] ='.format(len(a),i),a[:len(a):i], '\n')


a[0:12:1] = [ 0  1  2  3  4  5  6  7  8  9 10 11] 

a[:12:1] = [ 0  1  2  3  4  5  6  7  8  9 10 11] 

a[0:12:2] = [ 0  2  4  6  8 10] 

a[0:12:3] = [0 3 6 9] 

a[0:12:4] = [0 4 8] 

Ahora con el for 

a[:12:1] = [ 0  1  2  3  4  5  6  7  8  9 10 11] 

a[:12:2] = [ 0  2  4  6  8 10] 

a[:12:3] = [0 3 6 9] 

a[:12:4] = [0 4 8] 



In [67]:
# Si utilizamos un incremento negativo, el array se muestra en orden inverso

# El problema es que no muestra el valor 0
print('a[{}:0:-1] ='.format(len(a)), a[len(a):0:-1], '\n')
# Si se omiten los valores de índice, el resultado es preciso
print('a[::-1] =', a[::-1])

a[12:0:-1] = [11 10  9  8  7  6  5  4  3  2  1] 

a[::-1] = [11 10  9  8  7  6  5  4  3  2  1  0]


In [72]:
# Utilización de arreglos multidimensionales

b = np.arange(36).reshape(3,2,6)
print('b =\n', b)
# La instrucción reshape genera una matriz con 2 bloques, 3 filas y 4 columnas
# El número total de elementos es de 24 (generados por arange)

b =
 [[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [78]:
# Acceso individual a los elementos del array
# Elemento en el bloque 1, fila 1, columna 1
print('b[1,2,3] =', b[1,1,1], '\n')
# Elemento en el bloque 0, fila 1, columna 2
print('b[0,2,2] =', b[0,1,2], '\n')
# Elemento en el bloque 2, fila 1, columna 1
print('b[0,1,1] =', b[2,1,1])

b[1,2,3] = 19 

b[0,2,2] = 8 

b[0,1,1] = 31


In [114]:
#Vista de la matriz 
print('b =\n', b, '\n')

#Vista de la matriz por arreglos
for i in range(len(b)):
    print('b[{}] ='.format(i) , b[i],'\n')

#Vista de la matriz por elementos
for i in range(len(b)):
      for j in range(len(b[i])):
        print('b[{},{}] ='.format(i,j) , b[i][j],'\n')

b =
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]] 

b[0] = [ 0  1  2  3  4  5  6  7  8  9 10 11] 

b[1] = [12 13 14 15 16 17 18 19 20 21 22 23] 

b[2] = [24 25 26 27 28 29 30 31 32 33 34 35] 

b[0,0] = 0 

b[0,1] = 1 

b[0,2] = 2 

b[0,3] = 3 

b[0,4] = 4 

b[0,5] = 5 

b[0,6] = 6 

b[0,7] = 7 

b[0,8] = 8 

b[0,9] = 9 

b[0,10] = 10 

b[0,11] = 11 

b[1,0] = 12 

b[1,1] = 13 

b[1,2] = 14 

b[1,3] = 15 

b[1,4] = 16 

b[1,5] = 17 

b[1,6] = 18 

b[1,7] = 19 

b[1,8] = 20 

b[1,9] = 21 

b[1,10] = 22 

b[1,11] = 23 

b[2,0] = 24 

b[2,1] = 25 

b[2,2] = 26 

b[2,3] = 27 

b[2,4] = 28 

b[2,5] = 29 

b[2,6] = 30 

b[2,7] = 31 

b[2,8] = 32 

b[2,9] = 33 

b[2,10] = 34 

b[2,11] = 35 



In [90]:
# Mostraremos como generalizar una selección

# Primero elegimos el componente en la fila 0, columna 0, del bloque 0
print('b[0,0,0] =', b[0,0,0], '\n')
# A continuación, elegimos el componente en la fila 0, columna, pero del bloque 1
print('b[1,0,0] =', b[1,0,0], '\n')
# Para elegir SIMULTANEAMENTE ambos elementos, lo hacemos utilizando dos puntos
print('b[:,0,0] =', b[:,0,0])

b[0,0,0] = 0 

b[1,0,0] = 12 

b[:,0,0] = [ 0 12 24]


In [116]:
# Si escribimos: b[1]

# Habremos elegido el segundo bloque, pero habríamos omitido las filas y las columnas
# En tal caso, numpy toma todas las filas y columnas del bloque 0
print('b[0] =\n', b[0])

b[0] =
 [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [94]:
# Otra forma de representar b[0] es: b[0, :, :]

# Los dos puntos sin ningún valor, indican que se utilizarán todos los términos disponibles
# En este caso, todas las filas y todas las columnas
print('b[0,:,:] =\n', b[0,:,:])

b[0,:,:] =
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [95]:
# Cuando se utiliza la notación de : a derecha o a izquierda, se puede reemplazar por ...
# El ejemplo anterior se puede escribir así:
print('b[0, ...] =\n', b[0, ...])

b[0, ...] =
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [96]:
# Si queremos la fila 1 en el bloque 0 (sin que importen las columnas), se tiene:
print('b[0,1] =', b[0,1])

b[0,1] = [ 6  7  8  9 10 11]


In [97]:
# El resultado de una selección puede utilizar luego para un cálculo posterior

# Se obtiene la fila 1 del bloque 0 (como en ejemplo anterior)
# y se asigna dicha respuesta a la variable z 
z = b[0,1]
print('z =', z, '\n')
# En este caso, la variable z toma el valor: [4 5 6 7]
# Si ahora queremos tomar de dicha respuesta los valores de 2 en 2, se tiene:
print('z[::2] =', z[::2])

z = [ 6  7  8  9 10 11] 

z[::2] = [ 6  8 10]


In [98]:
# El ejercicio anterior se puede combinar en una expresión única, así:

print('b[0,1,::2] =', b[0,1,::2])
# Esta es una solución más compacta

b[0,1,::2] = [ 6  8 10]


In [99]:
# Imprime todas las columnas, independientemente de los bloques y filas

print(b, '\n')
print('b[:,:,1] =\n', b[:,:,1], '\n')
# Variante de notación (simplificada)
print('b[...,1] =\n', b[...,1])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]] 

b[:,:,1] =
 [[ 1  7]
 [13 19]
 [25 31]] 

b[...,1] =
 [[ 1  7]
 [13 19]
 [25 31]]


In [100]:
# Si queremos seleccionar todas las filas 2, independientemente

# de los bloques y columnas, se tiene:
print(b, '\n')
print('b[:,1] =', b[:,1])
# Puesto que no se menciona en la notación las columnas, se toman todos
# los valores según corresponda

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]] 

b[:,1] = [[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]
 [30 31 32 33 34 35]]


In [101]:
# En el siguiente ejemplo seleccionmos la columna 1 del bloque 0

print(b, '\n')
print('b[0,:,1] =', b[0,:,1])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]] 

b[0,:,1] = [1 7]


In [102]:
# Si queremos seleccionar la última columna del primer bloque, tenemos:

print('b[0,:,-1] =', b[0,:,-1])
# Podemos observar lo siguiente: entre corchetes encontramos tres valores
# El primero, el cero, selecciona el primer bloque
# El tercero, -1, se encarga de seleccionar la última columna
# Los dos puntos, en la segunda posición, SELECCIONAN todos los
# componentes de lad FILAS, que FORMARÁN PARTE de dicha COLUMNA
# Dado que los dos puntos definen todos los valores de las FILAS en
# una columna específica, si quisieramos que DICHOS VALORES estuvieran
# en orden inverso, ejecutaríamos la instrucción
print('b[0, ::-1, -1] =', b[0, ::-1, -1])
# La expresión ::-1 invierte todos los valores que se hubieran seleccionado
# Si en lugar de invertir la columna, quisieramos imprimir sus
# valores de 2 en 2, tendríamos:
print('b[0, ::2, -1] =', b[0, ::2, -1])

b[0,:,-1] = [ 5 11]
b[0, ::-1, -1] = [11  5]
b[0, ::2, -1] = [5]


In [103]:
# El array original

print(b, '\n-----------------------\n')
# Esta instrucción invierte los bloques
print(b[::-1])

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]] 
-----------------------

[[[24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]]


In [104]:
# La instrucción: ravel(), de-construye el efecto de la instrucción: reshape

# Este es el array b en su estado matricial
print('Matriz b =\n', b, '\n--------------------------\n')
# Con ravel() se genera un vector a partir de la matriz
print('Vector b = \n', b.ravel())

Matriz b =
 [[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]]

 [[12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[24 25 26 27 28 29]
  [30 31 32 33 34 35]]] 
--------------------------

Vector b = 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [105]:
# La instrucción: flatten() es similar a ravel()

# La diferencia es que flatten genera un nuevo espacio de memoria
print('Vector b con flatten =\n', b.flatten())

Vector b con flatten =
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [107]:
# Se puede cambiar la estructura de una matriz con la instrucción: shape

# Transformamos la matriz en 6 filas x 4 columnas
b.shape = (6,6)
print('b(6x6) =\n', b)

b(6x6) =
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [108]:
# A partir de la matriz que acaba de ser generada, vamos a mostrar

# como se construye la transpuesta de la matriz
# Matriz original
print('b =\n', b, '\n------------------------\n')
# Matri transpuesta
print('Transpuesta de b =\n', b.transpose(), '\n------------------------\n')

b =
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]] 
------------------------

Transpuesta de b =
 [[ 0  6 12 18 24 30]
 [ 1  7 13 19 25 31]
 [ 2  8 14 20 26 32]
 [ 3  9 15 21 27 33]
 [ 4 10 16 22 28 34]
 [ 5 11 17 23 29 35]] 
------------------------



In [109]:
# Para concluir este primer módulo de numpy, mostraremos que la instrucción

# resize, ejecuta una labor similar a reshape
# La diferencia está en que resize altera la estructura del array
# En cambio reshape crea una copia del original, razón por la cual en
# reshape se debe asignar el resultado a una nueva variable
# Se cambia la estructura del array b
b.resize([3,12])
# Al imprimir el array b, se observa que su estructura ha cambiado
print('b =\n', b)

b =
 [[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31 32 33 34 35]]
